# Generated by Django 4.2.10 on 2026-03-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_priority_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
